<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-01-21T13:55:29 IST" name="Default suite" finished-at="2021-01-21T13:55:45 IST" duration-ms="15973">
    <groups>
    </groups>
    <test started-at="2021-01-21T13:55:29 IST" name="Default test" finished-at="2021-01-21T13:55:45 IST" duration-ms="15973">
      <class name="com.suite1.testdata.TC_01_MagicBricks">
        <test-method is-config="true" signature="Before()[pri:0, instance:com.suite1.testdata.TC_01_MagicBricks@71b1176b]" started-at="2021-01-21T13:55:29 IST" name="Before" finished-at="2021-01-21T13:55:42 IST" duration-ms="12730" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Before -->
        <test-method signature="MagicBricksTestCase()[pri:0, instance:com.suite1.testdata.TC_01_MagicBricks@71b1176b]" started-at="2021-01-21T13:55:42 IST" name="MagicBricksTestCase" finished-at="2021-01-21T13:55:42 IST" duration-ms="28" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.suite1.testdata.MagicBricks.help(MagicBricks.java:68)
at com.suite1.testdata.TC_01_MagicBricks.MagicBricksTestCase(TC_01_MagicBricks.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MagicBricksTestCase -->
        <test-method is-config="true" signature="After()[pri:0, instance:com.suite1.testdata.TC_01_MagicBricks@71b1176b]" started-at="2021-01-21T13:55:42 IST" name="After" finished-at="2021-01-21T13:55:45 IST" duration-ms="3113" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- After -->
      </class> <!-- com.suite1.testdata.TC_01_MagicBricks -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
